# @package _global_
camera_name: camerahmr_calibrated_foreground_undistorted
dataset:
   camera_type: camerahmr_calibrated_foreground_undistorted_no_arah/camerahmr_calibrated_foreground_undistorted.pkl