# @package _global_

dataset_name: ps_male_3_camerahmr_multiple

dataset:
  name: people_snapshot_multiple
  root_dir: "../../data/peoplesnapshot_arah-format/people_snapshot_public"
  subject: male-3-casual
  camera_name: cameras
  smpl_model_path: camerahmr_multiple

  train_frames: [ 0, 456, 4 ]
  val_frames: [ 456, 457, 4 ]
  test_frames:
    pose: [ 456, 676, 4 ]
    all: [ 0, 676, 1 ]
  predict_frames: [0, 0, 1]

  img_hw:
    - 540
    - 540

  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
